spring:
  h2:
    console:
      enabled: true
      path: /h2

  datasource:
    url: jdbc:h2:mem:test
  mvc:
    path match:
      matching-strategy: ant_path_matcher

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        time_zone: +09:00
        use_sql_comments: true

  sql:
    init:
      data-locations: classpath*:db/h2/data.sql

mail:
  address:
    admin: jinhuizu@gmail.com
jwt:
  key: ${JWT_SECRET_KEY}
  access-token-expiration-minutes: 30
  refresh-token-expiration-minutes: 300
redis:
  host: localhost
  port: 6379
  password:
  timeout: 3000
  lettuce:
    pool:
      max-active: 8
      max-idle: 8
      min-idle: 0
