spring:
  datasource:
    username: admin
    url: jdbc:mysql://huijumain30.cwvzsuh16bdl.ap-northeast-2.rds.amazonaws.com:3306/huijumain30
    password: 12345678
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

mail:
  address:
    admin: jinhuizu@gmail.com
jwt:
  key: main301234567818383737462928272181817273543353458973498679438698476945874962djngkdngkjkjgbdfjkbgdfjbgjrgdfrgrghskfjsdkfng
  access-token-expiration-minutes: 30
  refresh-token-expiration-minutes: 300
redis:
  host: localhost
  port: 6379
  password:
  timeout: 3000
  lettuce:
    pool:
      max-active: 8
      max-idle: 8
      min-idle: 0
